---
driver:
  name: vagrant
  vm_hostname: ipa.example.com

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.4.1

platforms:
  #  - name: ubuntu-12.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[freeipa::default]
    attributes:
      freeipa:
        hostname: ipa.example.com
