---
driver:
  name: vagrant

provisioner:
  name: chef_zero 
  require_chef_omnibus: 12.9.38

platforms:
  - name: centos-7.1

suites:
  - name: server
    run_list: "fc-freeipa::server"
    driver:
      vm_hostname: server.example.com
      network:
      - ["private_network", {ip: "192.168.222.2"}]
      customize:
        memory: 1024
        cpus: 2
    data_bags_path: "test/integration/data_bags" 
    encrypted_data_bag_secret_key_path: "test/integration/data_bags/encrypted_data_bag_secret"
    attributes:
      vagrant_ip: "192.168.222.2"
      freeipa:
        ipa_admin_password: "ipa_admin_password"
        server: 
          hostname: "server.example.com"
        replica:
          hostname: "replica.example.com"
          ipaddress: "192.168.222.3"
  - name: client 
    run_list: "fc-freeipa::client"
    policyfile: "test/policies/client.rb"
    driver:
      vm_hostname: client.example.com
      network:
      - ["private_network", {ip: "192.168.222.4"}]
      customize:
        memory: 1024
        cpus: 2
    attributes:
      vagrant_ip: "192.168.222.2"
      freeipa:
        ipa_admin_password: "ipa_admin_password"
        server: 
          hostname: "server.example.com"
