---
driver:
  name: vagrant
  vm_hostname: ipa.example.com
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.4.1
  environments_path: test/environments
  solo_rb:
    environment: kitchen

platforms:
  #  - name: ubuntu-12.04
   - name: centos-6.5
   - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[fc-freeipa::default]
    attributes:
