Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 12
Style/FileName:
  Enabled: false
